cities_and_zone_ids = {(u'Jordan', u'Amman'): 'Asia/Amman', 
                       (u'Canada', u'Toronto'): 'America/Toronto', 
                       (u'Argentina', u'Buenos Aires'): 'America/Argentina/Buenos_Aires',
                       (u'Australia', u'Sydney'): 'Australia/Sydney', 
                       (u'Russia', u'Moscow'): 'Europe/Moscow', 
                       (u'China', u'Shanghai'): 'Asia/Shanghai',
                       (u'Hungary', u'Budapest'): 'Europe/Budapest', 
                       (u'Ukraine', u'Kiev'): 'Europe/Kiev', 
                       (u'Austria', u'Vienna'): 'Europe/Vienna',
                       (u'Nigeria', u'Lagos'): 'Africa/Lagos', 
                       (u'Sweden', u'Stockholm'): 'Europe/Stockholm', 
                       (u'Sri Lanka', u'Colombo'): 'Asia/Colombo',
                       (u'Denmark', u'Copenhagen'): 'Europe/Copenhagen', 
                       (u'Bangladesh', u'Chittagong'): 'Asia/Dhaka',
                       (u'Malta', u'Valletta'): 'Europe/Malta', 
                       (u'Mexico', u'Mexico City'): 'America/Mexico_City', 
                       (u'Italy', u'Milan'): 'Europe/Rome',
                       (u'India', u'Mumbai'): 'Asia/Kolkata', 
                       (u'Hong Kong', u'Hong Kong'): 'Asia/Hong_Kong', 
                       (u'Norway', u'Oslo'): 'Europe/Oslo',
                       (u'South Africa', u'Johannesburg'): 'Africa/Johannesburg', 
                       (u'Brazil', u'S\xe3o Paulo'): 'America/Sao_Paulo',
                       (u'Taiwan (Republic of China)', u'Taipei'): 'Asia/Taipei', 
                       (u'United Kingdom', u'London'): 'Europe/London', 
                       (u'Vietnam', u'Hanoi'): 'Asia/Ho_Chi_Minh', 
                       (u'United States', u'New York'): 'America/New_York', 
                       (u'Malaysia', u'Kuala Lumpur'): 'Asia/Kuala_Lumpur',
                       (u'Luxembourg', u'Luxembourg City'): 'Europe/Luxembourg', 
                       (u'Poland', u'Warsaw'): 'Europe/Warsaw',
                       (u'Thailand', u'Bangkok'): 'Asia/Bangkok', 
                       (u'Switzerland', u'Zurich'): 'Europe/Zurich', 
                       (u'Finland', u'Helsinki'): 'Europe/Helsinki', 
                       (u'South Korea', u'Busan & Seoul'): 'Asia/Seoul', 
                       (u'Indonesia', u'Jakarta'): 'Asia/Jakarta',
                       (u'Singapore', u'Singapore'): 'Asia/Singapore', 
                       (u'Germany', u'Frankfurt'): 'Europe/Berlin',
                       (u'Portugal', u'Lisboa'): 'Europe/Lisbon', 
                       (u'Israel', u'Tel Aviv'): 'Asia/Jerusalem', 
                       (u'Switzerland', u'Berne'): 'Europe/Zurich',
                       (u'New Zealand', u'Wellington'): 'Pacific/Auckland', 
                       (u'Jamaica', u'Kingston'): 'America/Jamaica',
                       (u'Latvia', u'Riga'): 'Europe/Riga', 
                       (u'Saudi Arabia', u'Riyadh'): 'Asia/Riyadh', 
                       (u'Kenya', u'Nairobi'): 'Africa/Nairobi',
                       (u'Tanzania', u'Dar-es-Salaam'): 'Africa/Dar_es_Salaam', 
                       (u'Netherlands', u'Amsterdam'): 'Europe/Amsterdam',
                       (u'Lebanon', u'Beirut'): 'Asia/Beirut', 
                       (u'Vietnam', u'Hochiminh'): 'Asia/Ho_Chi_Minh', 
                       (u'China', u'Shenzhen'): 'Asia/Shanghai', 
                       (u'Japan', u'Tokyo'): 'Asia/Tokyo', 
                       (u'Turkey', u'Istanbul'): 'Asia/Istanbul', 
                       (u'Bangladesh', u'Dhaka'): 'Asia/Dhaka',
                       (u'Ireland', u'Dublin'): 'Europe/Dublin', 
                       (u'France', u'Paris'): 'Europe/Paris', 
                       (u'Pakistan', u'Karachi'): 'Asia/Karachi',
                       (u'Philippines', u'Manila'): 'Asia/Manila', 
                       (u'Spain', u'Madrid'): 'Europe/Madrid', 
                       (u'Germany', u'Eschborn'): 'Europe/Berlin'
}

def get_tz_zone_id(country, city):
  return cities_and_zone_ids[(country, city)]

